[package]
name = "qmpp-host"
version = "0.1.0"
authors = ["seth <rader.seth@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmer = "^2.0"
quake-util = "^0.1"
